from django.db import models

# Create your models here.
class WebRequest(models.Model):
    reqnum = models.IntegerField(primary_key=True)
    program = models.CharField(max_length=1)
    rqdate = models.DateField()
    lqnum = models.CharField(max_length=3, blank=True, null=True)
    hqnum = models.CharField(max_length=3, blank=True, null=True)
    qlen = models.CharField(max_length=2, blank=True, null=True)
    nkeys = models.CharField(max_length=1, blank=True, null=True)
    a = models.CharField(max_length=1, blank=True, null=True)
    b = models.CharField(max_length=1, blank=True, null=True)
    c = models.CharField(max_length=1, blank=True, null=True)
    d = models.CharField(max_length=1, blank=True, null=True)
    e = models.CharField(max_length=1, blank=True, null=True)
    f = models.CharField(max_length=1, blank=True, null=True)
    k = models.CharField(max_length=1, blank=True, null=True)
    l = models.CharField(max_length=1, blank=True, null=True)
    m = models.CharField(max_length=1, blank=True, null=True)
    n = models.CharField(max_length=1, blank=True, null=True)
    o = models.CharField(max_length=1, blank=True, null=True)
    p = models.CharField(max_length=1, blank=True, null=True)
    pocketflag = models.CharField(max_length=1, blank=True, null=True)
    initials = models.CharField(max_length=3, blank=True, null=True)
    coursetitle = models.CharField(max_length=16, blank=True, null=True)
    instructor_name = models.CharField(max_length=32, blank=True, null=True)
    email2 = models.CharField(max_length=60, blank=True, null=True)
    userid = models.CharField(max_length=10, blank=True, null=True)
    caddr1 = models.CharField(max_length=32, blank=True, null=True)
    caddr2 = models.CharField(max_length=32, blank=True, null=True)
    caddr3 = models.CharField(max_length=60, blank=True, null=True)
    email1 = models.CharField(max_length=60, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    operator = models.CharField(max_length=10, blank=True, null=True)
    speedcode = models.CharField(max_length=5, blank=True, null=True)
    accountnum = models.CharField(max_length=6, blank=True, null=True)
    payment = models.CharField(max_length=1, blank=True, null=True)
    afs_dir_name = models.CharField(max_length=10, blank=True, null=True)
    notes = models.CharField(max_length=1000, blank=True, null=True)
    submitted = models.DateField(blank=True, null=True)
    received = models.DateField(blank=True, null=True)
    returned = models.DateField(blank=True, null=True)
    hardcopy = models.CharField(max_length=1, blank=True, null=True)
    dept = models.CharField(max_length=4, blank=True, null=True)
    cancelled = models.DateField(blank=True, null=True)
    scanned = models.DateField(blank=True, null=True)
    scanner = models.CharField(max_length=1, blank=True, null=True)



class WebProcessing(models.Model):
    reqnum = models.IntegerField(primary_key=True)
    reportnum = models.IntegerField()
    reporttype = models.CharField(max_length=10, blank=True, null=True)
    parameters = models.CharField(max_length=100, blank=True, null=True)
    filename = models.CharField(max_length=100, blank=True, null=True)

